import {
  LayoutDashboard,
  Building2,
  Package,
  Boxes,
  ClipboardCheck,
  Users,
  Truck,
  ShoppingCart,
  Undo2,
  Receipt,
  BarChart3,
  DatabaseBackup,
  UserCog,
  ClipboardList,
  MonitorPlay,
} from "lucide-react";
import type { TranslationKey } from "@/lib/i18n/dictionary";

export const NAV_ITEMS: { href: string; icon: React.ElementType; key: TranslationKey }[] = [
  { href: "/dashboard", icon: LayoutDashboard, key: "nav_dashboard" },
  { href: "/businesses", icon: Building2, key: "nav_businesses" },
  { href: "/products", icon: Package, key: "nav_products" },
  { href: "/stock", icon: Boxes, key: "nav_stock" },
  { href: "/inventory", icon: ClipboardCheck, key: "nav_inventory" },
  { href: "/contacts?kind=customer", icon: Users, key: "nav_customers" },
  { href: "/contacts?kind=supplier", icon: Truck, key: "nav_suppliers" },
  { href: "/pos", icon: ShoppingCart, key: "nav_pos" },
  { href: "/orders", icon: ClipboardList, key: "nav_orders" },
  { href: "/subscriptions", icon: MonitorPlay, key: "nav_subscriptions" },
  { href: "/returns", icon: Undo2, key: "nav_returns" },
  { href: "/expenses", icon: Receipt, key: "nav_expenses" },
  { href: "/reports", icon: BarChart3, key: "nav_reports" },
  { href: "/backup", icon: DatabaseBackup, key: "nav_backup" },
  { href: "/users", icon: UserCog, key: "nav_users" },
];
